
CREATE TABLE BOOK (
  BOOKURL VARCHAR NOT NULL,
  TITLE VARCHAR NOT NULL,
  HASHTAG VARCHAR NOT NULL,
  BOOKMETA VARCHAR NOT NULL,
  NUMTWEETS INT NOT NULL,
  AUTHOR VARCHAR NOT NULL
);


CREATE TABLE BOOKMETA (
    BOOKURL VARCHAR NOT NULL,
    READERS INT,
    LANG VARCHAR,
    NUMTRANS INT,
    NUMPAGES INT,
    PRICE VARCHAR,
    COMPLETENESS VARCHAR
);


CREATE TABLE COMPLETENESS (
    BOOKURL VARCHAR NOT NULL,
    READERS INT,
    LANG VARCHAR,
    NUMTRANS INT,
    NUMPAGES INT,
    PRICE VARCHAR,
    COMPLETENESS VARCHAR
);

CREATE TABLE PRICE (
  BOOKURL VARCHAR NOT NULL,
  MINPRICE INT,
  MAXPRICE INT
);

CREATE TABLE AUTHORTWEETS(
  AUTHORURL VARCHAR NOT NULL,
  TWEETTEXT VARCHAR,
  TWEETURL VARCHAR,
  RETWEETCOUNT INT
);

CREATE TABLE AUTHOR(
  AUTHORURL VARCHAR NOT NULL,
  TWITTERHANDLE VARCHAR,
  TWITTERURL VARCHAR,
  LEANPUBURL VARCHAR
);

CREATE TABLE BOOKTWEETSBYNONAUTHOR(
  TWEETURL VARCHAR NOT NULL,
  BOOKURL VARCHAR NOT NULL,
  TWEETTEXT VARCHAR,
  RETWEETCOUNT INT,
  SENTIMENT VARCHAR,
  HASHTAG VARCHAR,
  ORIGINATORURL VARCHAR
);


CREATE TABLE BOOKTWEETSBYAUTHOR(
  AUTHORURL VARCHAR NOT NULL,
  TWEETURL VARCHAR NOT NULL,
  BOOKURL VARCHAR NOT NULL,
  TWEETTEXT VARCHAR,
  RETWEETCOUNT INT,
  SENTIMENT VARCHAR,
  HASHTAG VARCHAR,
  ORIGINATORURL VARCHAR
);
