
CREATE TABLE BOOKS (
  URL VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  HASHTAG VARCHAR(255) NOT NULL,
  BOOKMETA VARCHAR(255) NOT NULL,
  NUMTWEETS INT NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL
);
