
CREATE TABLE BOOK (
  BOOKURL VARCHAR NOT NULL,
  TITLE VARCHAR NOT NULL,
  HASHTAG VARCHAR NOT NULL,
  NUMTWEETS INT NOT NULL,
  AUTHORURL VARCHAR NOT NULL,
  READERS INT,
  LANG VARCHAR,
  NUMTRANS INT,
  NUMPAGES INT,
  MINPRICE INT,
  MAXPRICE INT,
  COMPLETEPERCENT INT,
  COMPLETETHRESHOLD BOOLEAN
);



CREATE TABLE AUTHORTWEETS(
  AUTHORURL VARCHAR NOT NULL,
  TWEETTEXT VARCHAR,
  TWEETURL VARCHAR,
  RETWEETCOUNT INT
);

CREATE TABLE AUTHOR(
  AUTHORURL VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  TWITTERHANDLE VARCHAR,
  TWITTERURL VARCHAR,
);

CREATE TABLE BOOKTWEETS(
  TWEETURL VARCHAR NOT NULL,
  BOOKURL VARCHAR NOT NULL,
  TWEETTEXT VARCHAR,
  RETWEETCOUNT INT,
  SENTIMENT VARCHAR,
  HASHTAG VARCHAR,
  ORIGINATORURL VARCHAR,
  BYAUTHOR BOOLEAN
);


